# Предподготовка данных

## 1. Загрузка и первичный осмотр данных

In [19]:
# устанавливаем первые библиотеки
!pip install gdown -q

import gdown
import pandas as pd

In [20]:
#file_id = '17MzyZfT-s8vLl7s0ww3xJ0awR8-TG0aS'

#gdown.download(f'https://drive.google.com/uc?id={file_id}', 'data.csv', quiet=False)
#после первой загрузки оставить закомментированным

In [21]:
df = pd.read_csv('data.csv', sep = ';', decimal = ',')
display(df.head())

,Год,Месяц,Компания,Бренд,Модель,Модификация,Год выпуска,Страна-производитель,Вид топлива,"Объём двиг, л,",...,Тип клиента,Форма расчета,Количество,"Цена, USD","Продажа, USD",Область,Сегментация 2013,Класс 2013,Сегментация Eng,Локализация производства
0,2019,Май,Mercur Auto,Audi,A3,TFSI,2018,Германия,Бензин,"1,4",...,Физ. Лицо,безналичный,1.0,28115.00,28115.00,г.Алматы,Легковые автомобили,C класс,C,Импорт
1,2019,Август,Mercur Auto,Audi,A3,TFSI,2018,Германия,Бензин,"1,4",...,Юр. Лицо,наличный,1.0,32246.99,32246.99,г.Алматы,Легковые автомобили,C класс,C,Импорт
2,2019,Апрель,Mercur Auto,Audi,A4,TFSI,2018,Германия,Бензин,"1,4",...,Физ. Лицо,безналичный,1.0,32000.00,32000.00,г.Алматы,Легковые автомобили,D класс,D,Импорт
3,2019,Июль,Mercur Auto,Audi,A4,TFSI,2018,Германия,Бензин,"1,4",...,Юр. Лицо,безналичный,1.0,31929.00,31929.00,г.Алматы,Легковые автомобили,D класс,D,Импорт
4,2019,Июль,Mercur Auto,Audi,A4,TFSI,2018,Германия,Бензин,"1,4",...,Физ. Лицо,наличный,1.0,31929.00,31929.00,г.Алматы,Легковые автомобили,D класс,D,Импорт

In [22]:
# выводим общую информацию о датасете
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39966 entries, 0 to 39965
Data columns (total 25 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Год                             39966 non-null  int64
 1   Месяц                           39966 non-null  object
 2   Компания                        39966 non-null  object
 3   Бренд                           39966 non-null  object
 4   Модель                          39966 non-null  object
 5   Модификация                     36375 non-null  object
 6   Год выпуска                     39465 non-null  object
 7   Страна-производитель            39966 non-null  object
 8   Вид топлива                     36826 non-null  object
 9   Объём двиг, л,                  35708 non-null  object
 10  Коробка передач                 36711 non-null  object
 11  Тип привода                     35677 non-null  object
 12  Сегмент                         33205 non-null  object
 13  Регион                          39966 non-null  object
 14  Наименование дилерского центра  39966 non-null  object
 15  Тип клиента                     32919 non-null  object
 16  Форма расчета                   14038 non-null  object
 17  Количество                      39960 non-null  float64
 18  Цена, USD                       39966 non-null  float64
 19  Продажа, USD                    39966 non-null  float64
 20  Область                         39966 non-null  object
 21  Сегментация 2013                39966 non-null  object
 22  Класс 2013                      39966 non-null  object
 23  Сегментация Eng                 39966 non-null  object
 24  Локализация производства        39966 non-null  object
dtypes: float64(3), int64(1), object(21)
memory usage: 7.6+ MB

видим, что типы данных соответствуют значениям

In [23]:
# выводим суммарное число пропусков
df.isna().sum()

Год                                   0
Месяц                                 0
Компания                              0
Бренд                                 0
Модель                                0
Модификация                        3591
Год выпуска                         501
Страна-производитель                  0
Вид топлива                        3140
Объём двиг, л,                     4258
Коробка передач                    3255
Тип привода                        4289
Сегмент                            6761
Регион                                0
Наименование дилерского центра        0
Тип клиента                        7047
Форма расчета                     25928
Количество                            6
Цена, USD                             0
Продажа, USD                          0
Область                               0
Сегментация 2013                      0
Класс 2013                            0
Сегментация Eng                       0
Локализация производства              0
dtype: int64

да, пропусков у нас местами много, будем подправлять
удалим столбцы, содержащие критическое количество пропусков или не енсущие в себе пользы
для дальнейшего анализа.

In [24]:
col_drop = [ 'Компания', 'Форма расчета', 'Сегмент', 'Сегментация Eng', 'Локализация производства', 'Тип клиента', 'Модификация']
df.drop(columns = col_drop , inplace = True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39966 entries, 0 to 39965
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Год                             39966 non-null  int64
 1   Месяц                           39966 non-null  object
 2   Бренд                           39966 non-null  object
 3   Модель                          39966 non-null  object
 4   Год выпуска                     39465 non-null  object
 5   Страна-производитель            39966 non-null  object
 6   Вид топлива                     36826 non-null  object
 7   Объём двиг, л,                  35708 non-null  object
 8   Коробка передач                 36711 non-null  object
 9   Тип привода                     35677 non-null  object
 10  Регион                          39966 non-null  object
 11  Наименование дилерского центра  39966 non-null  object
 12  Количество                      39960 non-null  float64
 13  Цена, USD                       39966 non-null  float64
 14  Продажа, USD                    39966 non-null  float64
 15  Область                         39966 non-null  object
 16  Сегментация 2013                39966 non-null  object
 17  Класс 2013                      39966 non-null  object
dtypes: float64(3), int64(1), object(14)
memory usage: 5.5+ MB

In [26]:
# вполне полноценный датасет получается, а теперь переименуем названия столбцов
df.columns = ['year', 
              'month',
              'brand',
              'model',
              'manufacture_year',
              'manufacture_contry',
              'fuel_type',
              'engine_volume',
              'transmission',
              'drive_type',
              'region',
              'dealer',
              'amount',
              'price_usd',
              'sale_usd',
              'area',
              'segmentation',
              'class']

In [30]:
df = df.drop_duplicates()
df = df.dropna(how = 'all')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17978 entries, 0 to 39951
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   year                17978 non-null  int64
 1   month               17978 non-null  object
 2   brand               17978 non-null  object
 3   model               17978 non-null  object
 4   manufacture_year    17779 non-null  object
 5   manufacture_contry  17978 non-null  object
 6   fuel_type           16801 non-null  object
 7   engine_volume       16424 non-null  object
 8   transmission        16835 non-null  object
 9   drive_type          16489 non-null  object
 10  region              17978 non-null  object
 11  dealer              17978 non-null  object
 12  amount              17972 non-null  float64
 13  price_usd           17978 non-null  float64
 14  sale_usd            17978 non-null  float64
 15  area                17978 non-null  object
 16  segmentation        17978 non-null  object
 17  class               17978 non-null  object
dtypes: float64(3), int64(1), object(14)
memory usage: 2.6+ MB

In [31]:
df.head()

,year,month,brand,model,manufacture_year,manufacture_contry,fuel_type,engine_volume,transmission,drive_type,region,dealer,amount,price_usd,sale_usd,area,segmentation,class
0,2019,Май,Audi,A3,2018,Германия,Бензин,"1,4",S-tronic,передний,Алматы,Mercur Auto Алматы,1.0,28115.00000,28115.00000,г.Алматы,Легковые автомобили,C класс
1,2019,Август,Audi,A3,2018,Германия,Бензин,"1,4",S-tronic,передний,Алматы,Mercur Auto Алматы,1.0,32246.99000,32246.99000,г.Алматы,Легковые автомобили,C класс
2,2019,Апрель,Audi,A4,2018,Германия,Бензин,"1,4",S-Tronic,FWD,Алматы,Mercur Auto Алматы,1.0,32000.00000,32000.00000,г.Алматы,Легковые автомобили,D класс
3,2019,Июль,Audi,A4,2018,Германия,Бензин,"1,4",S-tronic,передний,Алматы,Mercur Auto Алматы,1.0,31929.00000,31929.00000,г.Алматы,Легковые автомобили,D класс
5,2019,Февраль,Audi,A6,2017,Германия,Бензин,2,S-Tronic,quattro,Нур-Султан,Mercur Auto Астана,1.0,42608.25485,42608.25485,г.Нур-Султан,Легковые автомобили,E класс